import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import payment_support

def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(payment_support.root, tearoff=0)
        Popupmenu1.configure(activebackground="beige")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#000000")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="#000000")
        Popupmenu1.post(event.x_root, event.y_root)

def popup2(event, *args, **kwargs):
        Popupmenu2 = tk.Menu(payment_support.root, tearoff=0)
        Popupmenu2.configure(activebackground="beige")
        Popupmenu2.configure(activeborderwidth="1")
        Popupmenu2.configure(activeforeground="#000000")
        Popupmenu2.configure(background="#d9d9d9")
        Popupmenu2.configure(borderwidth="1")
        Popupmenu2.configure(disabledforeground="#a3a3a3")
        Popupmenu2.configure(foreground="#000000")
        Popupmenu2.post(event.x_root, event.y_root)

def popup3(event, *args, **kwargs):
        Popupmenu3 = tk.Menu(payment_support.root, tearoff=0)
        Popupmenu3.configure(activebackground="beige")
        Popupmenu3.configure(activeborderwidth="1")
        Popupmenu3.configure(activeforeground="#000000")
        Popupmenu3.configure(background="#d9d9d9")
        Popupmenu3.configure(borderwidth="1")
        Popupmenu3.configure(disabledforeground="#a3a3a3")
        Popupmenu3.configure(foreground="#000000")
        Popupmenu3.post(event.x_root, event.y_root)

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("1920x1009+-51+62")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#b7ecfb")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.865, rely=0.089, relheight=0.915
                , relwidth=0.132)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#66ddf2")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Button9 = tk.Button(self.Frame1)
        self.Button9.place(relx=0.0, rely=0.011, height=24, width=257)
        self.Button9.configure(activebackground="beige")
        self.Button9.configure(activeforeground="#000000")
        self.Button9.configure(background="#ffffff")
        self.Button9.configure(compound='left')
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0")
        self.Button9.configure(text='''F3 : Date''')

        self.but50 = tk.Button(self.top)
        self.but50.place(relx=0.099, rely=0.03, height=34, width=117)
        self.but50.configure(activebackground="#0000ff")
        self.but50.configure(activeforeground="white")
        self.but50.configure(activeforeground="#ffffff")
        self.but50.configure(background="#ffffff")
        self.but50.configure(compound='left')
        self.but50.configure(disabledforeground="#a3a3a3")
        self.but50.configure(foreground="#000000")
        self.but50.configure(highlightbackground="#d9d9d9")
        self.but50.configure(highlightcolor="black")
        self.but50.configure(pady="0")
        self.but50.configure(text='''K : Company''')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.177, rely=0.03, height=34, width=117)
        self.Button1.configure(activebackground="beige")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Button''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.255, rely=0.03, height=34, width=117)
        self.Button2.configure(activebackground="beige")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#ffffff")
        self.Button2.configure(borderwidth="1")
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Button''')

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.401, rely=0.03, height=34, width=117)
        self.Button3.configure(activebackground="beige")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#ffffff")
        self.Button3.configure(compound='left')
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''G : Goto''')

        self.Button4 = tk.Button(self.top)
        self.Button4.place(relx=0.719, rely=0.03, height=34, width=127)
        self.Button4.configure(activebackground="beige")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#ffffff")
        self.Button4.configure(compound='left')
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''E : Email''')

        self.Button5 = tk.Button(self.top)
        self.Button5.place(relx=0.62, rely=0.03, height=34, width=117)
        self.Button5.configure(activebackground="beige")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#ffffff")
        self.Button5.configure(compound='left')
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''M :Export''')

        self.Button6 = tk.Button(self.top)
        self.Button6.place(relx=0.813, rely=0.03, height=34, width=117)
        self.Button6.configure(activebackground="beige")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#ffffff")
        self.Button6.configure(compound='left')
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''P : Print''')

        self.Button7 = tk.Button(self.top)
        self.Button7.place(relx=0.901, rely=0.03, height=34, width=117)
        self.Button7.configure(activebackground="beige")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#ffffff")
        self.Button7.configure(compound='left')
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(text='''F1 : Help''')

        self.Button8 = tk.Button(self.top)
        self.Button8.place(relx=0.536, rely=0.03, height=34, width=117)
        self.Button8.configure(activebackground="beige")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#ffffff")
        self.Button8.configure(compound='left')
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(text='''I : Import''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Button17 = tk.Button(self.top)
        self.Button17.place(relx=0.005, rely=0.02, height=44, width=157)
        self.Button17.configure(activebackground="beige")
        self.Button17.configure(activeforeground="#000000")
        self.Button17.configure(background="#b7ecfb")
        self.Button17.configure(borderwidth="0")
        self.Button17.configure(compound='left')
        self.Button17.configure(disabledforeground="#a3a3a3")
        self.Button17.configure(font="-family {Bahnschrift Light SemiCondensed} -size 24 -weight bold")
        self.Button17.configure(foreground="#000000")
        self.Button17.configure(highlightbackground="#d9d9d9")
        self.Button17.configure(highlightcolor="black")
        self.Button17.configure(pady="0")
        self.Button17.configure(text='''Tally Prime''')

        self.Frame5 = tk.Frame(self.top)
        self.Frame5.place(relx=0.0, rely=0.089, relheight=0.035, relwidth=0.867)
        self.Frame5.configure(relief='groove')
        self.Frame5.configure(borderwidth="2")
        self.Frame5.configure(relief="groove")
        self.Frame5.configure(background="#41b4f1")
        self.Frame5.configure(highlightbackground="#d9d9d9")
        self.Frame5.configure(highlightcolor="#0f8bce")

        self.Button19 = tk.Button(self.Frame5)
        self.Button19.place(relx=0.018, rely=0.286, height=14, width=107)
        self.Button19.configure(activebackground="beige")
        self.Button19.configure(activeforeground="#000000")
        self.Button19.configure(background="#41b4f1")
        self.Button19.configure(borderwidth="0")
        self.Button19.configure(compound='left')
        self.Button19.configure(disabledforeground="#a3a3a3")
        self.Button19.configure(foreground="#000000")
        self.Button19.configure(highlightbackground="#d9d9d9")
        self.Button19.configure(highlightcolor="black")
        self.Button19.configure(pady="0")
        self.Button19.configure(text='''Payment Register''')

        self.Frame2 = tk.Frame(self.top)
        self.Frame2.place(relx=0.0, rely=0.119, relheight=0.887, relwidth=0.867)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#ffffff")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Frame3 = tk.Frame(self.Frame2)
        self.Frame3.place(relx=0.0, rely=0.011, relheight=0.162, relwidth=1.0)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#ffffff")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="black")

        self.Frame4 = tk.Frame(self.Frame3)
        self.Frame4.place(relx=0.0, rely=0.0, relheight=0.993, relwidth=0.778)
        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief="groove")
        self.Frame4.configure(background="#ffffff")
        self.Frame4.configure(highlightbackground="#d9d9d9")
        self.Frame4.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame4)
        self.Label1.place(relx=0.008, rely=0.208, height=41, width=145)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(borderwidth="0")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Century} -size 17")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Particulars''')

        self.Frame6 = tk.Frame(self.Frame3)
        self.Frame6.place(relx=0.775, rely=0.0, relheight=0.524, relwidth=0.225)
        self.Frame6.configure(relief='groove')
        self.Frame6.configure(borderwidth="2")
        self.Frame6.configure(relief="groove")
        self.Frame6.configure(background="#ffffff")
        self.Frame6.configure(highlightbackground="#d9d9d9")
        self.Frame6.configure(highlightcolor="black")

        self.Label2 = tk.Label(self.Frame6)
        self.Label2.place(relx=0.4, rely=0.118, height=19, width=124)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Payment''')

        self.Frame7 = tk.Frame(self.Frame3)
        self.Frame7.place(relx=0.775, rely=0.483, relheight=0.31, relwidth=0.225)

        self.Frame7.configure(relief='groove')
        self.Frame7.configure(borderwidth="2")
        self.Frame7.configure(relief="groove")
        self.Frame7.configure(background="#ffffff")
        self.Frame7.configure(highlightbackground="#d9d9d9")
        self.Frame7.configure(highlightcolor="black")

        self.Label3 = tk.Label(self.Frame7)
        self.Label3.place(relx=0.373, rely=0.2, height=30, width=84)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Transactions''')

        self.Frame8 = tk.Frame(self.Frame3)
        self.Frame8.place(relx=0.775, rely=0.759, relheight=0.241
                , relwidth=0.117)
        self.Frame8.configure(relief='groove')
        self.Frame8.configure(borderwidth="2")
        self.Frame8.configure(relief="groove")
        self.Frame8.configure(background="#ffffff")
        self.Frame8.configure(highlightbackground="#d9d9d9")
        self.Frame8.configure(highlightcolor="black")

        self.Label4 = tk.Label(self.Frame8)
        self.Label4.place(relx=0.205, rely=0.257, height=21, width=124)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Total Vouchers''')

        self.Frame9 = tk.Frame(self.Frame3)
        self.Frame9.place(relx=0.889, rely=0.759, relheight=0.241
                , relwidth=0.111)
        self.Frame9.configure(relief='groove')
        self.Frame9.configure(borderwidth="2")
        self.Frame9.configure(relief="groove")
        self.Frame9.configure(background="#ffffff")
        self.Frame9.configure(highlightbackground="#d9d9d9")
        self.Frame9.configure(highlightcolor="black")

        self.Label5 = tk.Label(self.Frame9)
        self.Label5.place(relx=0.324, rely=0.257, height=21, width=104)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''(Cancelled)''')

        self.Frame10 = tk.Frame(self.Frame2)
        self.Frame10.place(relx=0.0, rely=0.168, relheight=0.051, relwidth=1.0)
        self.Frame10.configure(relief='groove')
        self.Frame10.configure(borderwidth="2")
        self.Frame10.configure(relief="groove")
        self.Frame10.configure(background="#ffffff")
        self.Frame10.configure(highlightbackground="#d9d9d9")
        self.Frame10.configure(highlightcolor="#ffffff")

        self.Frame11 = tk.Frame(self.Frame2)
        self.Frame11.place(relx=0.0, rely=0.212, relheight=0.788, relwidth=1.0)
        self.Frame11.configure(relief='groove')
        self.Frame11.configure(borderwidth="2")
        self.Frame11.configure(relief="groove")
        self.Frame11.configure(background="#ffffff")
        self.Frame11.configure(highlightbackground="#d9d9d9")
        self.Frame11.configure(highlightcolor="black")

        self.Button10 = tk.Button(self.Frame11)
        self.Button10.place(relx=0.0, rely=0.014, height=14, width=167)
        self.Button10.configure(activebackground="beige")
        self.Button10.configure(activeforeground="#000000")
        self.Button10.configure(background="#ffffff")
        self.Button10.configure(borderwidth="0")
        self.Button10.configure(compound='left')
        self.Button10.configure(disabledforeground="#a3a3a3")
        self.Button10.configure(font="-family {Segoe UI} -size 9")
        self.Button10.configure(foreground="#000000")
        self.Button10.configure(highlightbackground="#d9d9d9")
        self.Button10.configure(highlightcolor="black")
        self.Button10.configure(pady="0")
        self.Button10.configure(text='''April''')

        self.Button11 = tk.Button(self.Frame11)
        self.Button11.place(relx=0.006, rely=0.043, height=24, width=147)
        self.Button11.configure(activebackground="beige")
        self.Button11.configure(activeforeground="#000000")
        self.Button11.configure(background="#ffffff")
        self.Button11.configure(borderwidth="0")
        self.Button11.configure(compound='left')
        self.Button11.configure(disabledforeground="#a3a3a3")
        self.Button11.configure(foreground="#000000")
        self.Button11.configure(highlightbackground="#d9d9d9")
        self.Button11.configure(highlightcolor="black")
        self.Button11.configure(pady="0")
        self.Button11.configure(text='''May''')

        self.Button12 = tk.Button(self.Frame11)
        self.Button12.place(relx=0.006, rely=0.072, height=24, width=147)
        self.Button12.configure(activebackground="beige")
        self.Button12.configure(activeforeground="#000000")
        self.Button12.configure(background="#ffffff")
        self.Button12.configure(borderwidth="0")
        self.Button12.configure(compound='left')
        self.Button12.configure(disabledforeground="#a3a3a3")
        self.Button12.configure(foreground="#000000")
        self.Button12.configure(highlightbackground="#d9d9d9")
        self.Button12.configure(highlightcolor="black")
        self.Button12.configure(pady="0")
        self.Button12.configure(text='''June''')

        self.Button13 = tk.Button(self.Frame11)
        self.Button13.place(relx=0.006, rely=0.099, height=24, width=147)
        self.Button13.configure(activebackground="beige")
        self.Button13.configure(activeforeground="#000000")
        self.Button13.configure(background="#ffffff")
        self.Button13.configure(borderwidth="0")
        self.Button13.configure(compound='left')
        self.Button13.configure(disabledforeground="#a3a3a3")
        self.Button13.configure(foreground="#000000")
        self.Button13.configure(highlightbackground="#d9d9d9")
        self.Button13.configure(highlightcolor="black")
        self.Button13.configure(pady="0")
        self.Button13.configure(text='''July''')

        self.Button14 = tk.Button(self.Frame11)
        self.Button14.place(relx=0.006, rely=0.128, height=24, width=147)
        self.Button14.configure(activebackground="beige")
        self.Button14.configure(activeforeground="#000000")
        self.Button14.configure(background="#ffffff")
        self.Button14.configure(borderwidth="0")
        self.Button14.configure(compound='left')
        self.Button14.configure(disabledforeground="#a3a3a3")
        self.Button14.configure(foreground="#000000")
        self.Button14.configure(highlightbackground="#d9d9d9")
        self.Button14.configure(highlightcolor="black")
        self.Button14.configure(pady="0")
        self.Button14.configure(text='''August''')

        self.Button15 = tk.Button(self.Frame11)
        self.Button15.place(relx=0.006, rely=0.156, height=24, width=147)
        self.Button15.configure(activebackground="beige")
        self.Button15.configure(activeforeground="#000000")
        self.Button15.configure(background="#ffffff")
        self.Button15.configure(borderwidth="0")
        self.Button15.configure(compound='left')
        self.Button15.configure(disabledforeground="#a3a3a3")
        self.Button15.configure(foreground="#000000")
        self.Button15.configure(highlightbackground="#d9d9d9")
        self.Button15.configure(highlightcolor="black")
        self.Button15.configure(pady="0")
        self.Button15.configure(text='''September''')

        self.Button16 = tk.Button(self.Frame11)
        self.Button16.place(relx=0.006, rely=0.184, height=24, width=137)
        self.Button16.configure(activebackground="beige")
        self.Button16.configure(activeforeground="#000000")
        self.Button16.configure(background="#ffffff")
        self.Button16.configure(borderwidth="0")
        self.Button16.configure(compound='left')
        self.Button16.configure(disabledforeground="#a3a3a3")
        self.Button16.configure(foreground="#000000")
        self.Button16.configure(highlightbackground="#d9d9d9")
        self.Button16.configure(highlightcolor="black")
        self.Button16.configure(pady="0")
        self.Button16.configure(text='''October''')

        self.Button18 = tk.Button(self.Frame11)
        self.Button18.place(relx=0.006, rely=0.213, height=24, width=147)
        self.Button18.configure(activebackground="beige")
        self.Button18.configure(activeforeground="#000000")
        self.Button18.configure(background="#ffffff")
        self.Button18.configure(borderwidth="0")
        self.Button18.configure(compound='left')
        self.Button18.configure(disabledforeground="#a3a3a3")
        self.Button18.configure(foreground="#000000")
        self.Button18.configure(highlightbackground="#d9d9d9")
        self.Button18.configure(highlightcolor="black")
        self.Button18.configure(pady="0")
        self.Button18.configure(text='''November''')

        self.Button20 = tk.Button(self.Frame11)
        self.Button20.place(relx=0.006, rely=0.241, height=24, width=147)
        self.Button20.configure(activebackground="beige")
        self.Button20.configure(activeforeground="#000000")
        self.Button20.configure(background="#ffffff")
        self.Button20.configure(borderwidth="0")
        self.Button20.configure(compound='left')
        self.Button20.configure(disabledforeground="#a3a3a3")
        self.Button20.configure(foreground="#000000")
        self.Button20.configure(highlightbackground="#d9d9d9")
        self.Button20.configure(highlightcolor="black")
        self.Button20.configure(pady="0")
        self.Button20.configure(text='''December''')

        self.Button21 = tk.Button(self.Frame11)
        self.Button21.place(relx=0.006, rely=0.27, height=24, width=137)
        self.Button21.configure(activebackground="beige")
        self.Button21.configure(activeforeground="#000000")
        self.Button21.configure(background="#ffffff")
        self.Button21.configure(borderwidth="0")
        self.Button21.configure(compound='left')
        self.Button21.configure(disabledforeground="#a3a3a3")
        self.Button21.configure(foreground="#000000")
        self.Button21.configure(highlightbackground="#d9d9d9")
        self.Button21.configure(highlightcolor="black")
        self.Button21.configure(pady="0")
        self.Button21.configure(text='''January''')

        self.Button22 = tk.Button(self.Frame11)
        self.Button22.place(relx=0.0, rely=0.298, height=24, width=157)
        self.Button22.configure(activebackground="beige")
        self.Button22.configure(activeforeground="#000000")
        self.Button22.configure(background="#ffffff")
        self.Button22.configure(borderwidth="0")
        self.Button22.configure(compound='left')
        self.Button22.configure(disabledforeground="#a3a3a3")
        self.Button22.configure(foreground="#000000")
        self.Button22.configure(highlightbackground="#d9d9d9")
        self.Button22.configure(highlightcolor="black")
        self.Button22.configure(pady="0")
        self.Button22.configure(text='''February''')

        self.Button23 = tk.Button(self.Frame11)
        self.Button23.place(relx=0.006, rely=0.326, height=24, width=127)
        self.Button23.configure(activebackground="beige")
        self.Button23.configure(activeforeground="#000000")
        self.Button23.configure(background="#ffffff")
        self.Button23.configure(borderwidth="0")
        self.Button23.configure(compound='left')
        self.Button23.configure(disabledforeground="#a3a3a3")
        self.Button23.configure(foreground="#000000")
        self.Button23.configure(highlightbackground="#d9d9d9")
        self.Button23.configure(highlightcolor="black")
        self.Button23.configure(pady="0")
        self.Button23.configure(text='''March''')

        self.Frame12 = tk.Frame(self.Frame11)
        self.Frame12.place(relx=0.0, rely=0.936, relheight=0.064, relwidth=1.0)
        self.Frame12.configure(relief='groove')
        self.Frame12.configure(borderwidth="2")
        self.Frame12.configure(relief="groove")
        self.Frame12.configure(background="#ffffff")
        self.Frame12.configure(highlightbackground="#d9d9d9")
        self.Frame12.configure(highlightcolor="black")

        self.Label6 = tk.Label(self.Frame12)
        self.Label6.place(relx=0.018, rely=0.222, height=21, width=133)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#ffffff")
        self.Label6.configure(borderwidth="0")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Source Code Pro} -size 13")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Grand Total''')

class Toplevel2:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("600x450+956+260")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 1")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

def start_up():
    payment_support.main()

if __name__ == '__main__':
    payment_support.main()




